### ISSUE TITLE
Cant exit mail app, delete draft or save draft doesnt return back to app.

### ISSUE THREAD

**Issue by Mark-Leck** [disusered/cordova-open#18]
I have had this same issue while using fileopener2, I am not sure if this is an IOS, PG/Cordova issue or a plugin issue though.

Basically your plugin works as expected, case scenario:
1) Open a pdf file,
2) I then select export document (up arrow on page icon top right)
3) If I select adobe reader all is ok as it opens in its own new instance which can be dismissed separately as/when.
4) If I select the mail app, it opens in the same instance and as stated I can not return back to my app except for a close/restart.
mail works as expected ie: sends mail, but selecting delete draft or save draft doesn't return me back to my app. ie: It doesn't close.

Sorry if this is not the plugins fault, but I am at a loss to figure out why.

**Comment by Xalior** [comment]
https://github.com/pwlin/cordova-plugin-file-opener2/issues/17 seems to cover your problem, and perhaps your resolution, exactly? x

**Comment by Xalior** [comment]
Oh. Wait. That is you @Mark-Leck - never mind. Sorry!

**Comment by disusered** [comment]
I finally was able to look into this, I was not able to replicate on iOS 8.2 but I did find some issues with iOS7 due to deallocating early, as such I made some adjustments to the plugin lifecycle to run as a background thread, as well as changing the UIView context it runs to the default Cordova context. Hopefully these clear this up!
