### ISSUE TITLE
Problem found

### ISSUE THREAD

**Issue by pig2** [disusered/cordova-open#30]
Hi,
* is added to the access of config.xml.
Intranet documnet can be embedded in iframe of APP.
But any Intranet documents cannot be opened by the plugin. e.g. http://192.168.1.XXX/pork.pdf

Thanks.

**Comment by disusered** [comment]
Hi, I added a test for this situation and was unable to replicate it on iOS or Android. Given your other issue (#29), I believe you have not set up a Content-Security-Policy for acceptable domains.

In a [recent update](https://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html) this became mandatory. Since this plugin uses Cordova's FileTransfer plugin, it is subject to its rules.

You will need to add [cordova-plugin-whitelist](https://github.com/apache/cordova-plugin-whitelist) and set it up according to its README, then the plugin will work.
